### ISSUE TITLE
Can chisel do 1-indexed Vecs?

### ISSUE THREAD

**Issue by jwright6323** [ucb-bar/hbwif#4]
This would make the DFE tap Vecs a lot cleaner

**Comment by aswaterman** [comment]
1-indexed as in one-hot?  Mux1H(ones, vec) is the best way to go about that.

**Comment by jwright6323** [comment]
I meant _1, _2, _3, ... _N rather than one-hot. We have an analog block with an index starting at 1 instead of 0.

**Comment by aswaterman** [comment]
Ah, I see.  The 0-based indexing is baked in all over the place.  Maybe in some cases it's cleaner to prepend a dummy 0th element, so you can use the 1-based index directly without having to subtract.

**Comment by jwright6323** [comment]
Yeah, I think that's probably what we'll end up doing. Thanks
